/*
  # Add Seasonal Themed Offers

  1. New Offers
    - Add 5 specific winter offers (skiing, snowboarding, après-ski)
    - Add 5 specific spring offers (diving, trekking, city nature)
    - Add 5 specific summer offers (sailing, beach, water sports)
    - Add 5 specific autumn offers (city break, culture, gastronomy)

  2. Details
    - Each offer has season-specific activities and descriptions
    - All offers include images, pricing, and complete details
    - Offers are designed to match seasonal themes perfectly
*/

-- Winter Offers (skiing, snowboarding, après-ski)
INSERT INTO offers (
  title, description, short_description, destination, country, duration, price, original_price,
  images, meals, trip_type, season, is_last_minute, accommodation, transport, rating, review_count
) VALUES
(
  'Narty w Alpach Francuskich - Val d''Isère',
  'Odkryj magię zimowych Alp! Val d''Isère to jeden z najlepszych ośrodków narciarskich w Europie. 300 km tras, nowoczesne wyciągi, profesjonalna szkoła narciarska. Wieczorami après-ski w legendarnych barach górskich. Zakwaterowanie w komfortowym hotelu tuż przy stoku.',
  'Luksusowy wyjazd narciarski do Val d''Isère z pełnym wyposażeniem',
  'Val d''Isère',
  'Francja',
  7,
  4599,
  5299,
  ARRAY['https://images.pexels.com/photos/2433353/pexels-photo-2433353.jpeg', 'https://images.pexels.com/photos/848618/pexels-photo-848618.jpeg'],
  'HB',
  'adventure',
  'winter',
  false,
  'Hotel 4* przy stoku',
  'Autokar klimatyzowany',
  4.8,
  156
),
(
  'Snowboard w Austrii - Innsbruck',
  'Raj dla snowboardzistów! Innsbruck oferuje różnorodne trasy dla każdego poziomu zaawansowania. Snowpark z halfpipe i trampolinami. Wieczorne życie w centrum miasta. Możliwość kursu snowboardowego z instruktorem.',
  'Wyjazd snowboardowy do Innsbrucka z profesjonalną szkółką',
  'Innsbruck',
  'Austria',
  7,
  3899,
  4599,
  ARRAY['https://images.pexels.com/photos/2440025/pexels-photo-2440025.jpeg', 'https://images.pexels.com/photos/1430677/pexels-photo-1430677.jpeg'],
  'HB',
  'adventure',
  'winter',
  false,
  'Hotel 3* w centrum',
  'Autokar klimatyzowany',
  4.6,
  89
),
(
  'Narty w Dolomitach - Cortina d''Ampezzo',
  'Perła włoskich Alp! Spektakularne widoki na Dolomity, doskonałe trasy narciarskie, włoska gościnność. Po nartach relaks w SPA, wieczorem degustacja włoskiej kuchni i wina. Dla wymagających narciarzy i miłośników dolce vita.',
  'Luksusowe narty w Dolomitach z włoskim stylem',
  'Cortina d''Ampezzo',
  'Włochy',
  7,
  5299,
  6199,
  ARRAY['https://images.pexels.com/photos/2437297/pexels-photo-2437297.jpeg', 'https://images.pexels.com/photos/869258/pexels-photo-869258.jpeg'],
  'HB',
  'adventure',
  'winter',
  false,
  'Hotel 4* z SPA',
  'Autokar klimatyzowany',
  4.9,
  203
),
(
  'Zakopane - Narty w Tatrach',
  'Polskie góry zimą to niezapomniane przeżycie! Nowoczesne wyciągi na Kasprowym Wierchu i Gubałówce. Po nartach relaks w termach, wieczorem spacer po Krupówkach. Regionalna kuchnia i góralska atmosfera.',
  'Narty w polskich Tatrach z termami i regionalną kuchnią',
  'Zakopane',
  'Polska',
  5,
  1899,
  2299,
  ARRAY['https://images.pexels.com/photos/2166559/pexels-photo-2166559.jpeg', 'https://images.pexels.com/photos/1666021/pexels-photo-1666021.jpeg'],
  'HB',
  'adventure',
  'winter',
  false,
  'Hotel 3* w centrum',
  'Autokar',
  4.5,
  124
),
(
  'Szwajcaria - Zermatt i Matterhorn',
  'Ikona alpejskich kurortów narciarskich! Zermatt u stóp słynnego Matterhorn oferuje 360 km tras, lodowiec całoroczny, luksusowe hotele i ekskluzywne après-ski. Bezsamochodowe miasteczko z unikalną atmosferą.',
  'Premium narty w Zermatt z widokiem na Matterhorn',
  'Zermatt',
  'Szwajcaria',
  7,
  7899,
  9299,
  ARRAY['https://images.pexels.com/photos/1430676/pexels-photo-1430676.jpeg', 'https://images.pexels.com/photos/2403209/pexels-photo-2403209.jpeg'],
  'HB',
  'adventure',
  'winter',
  false,
  'Hotel 5* luksusowy',
  'Autokar klimatyzowany premium',
  5.0,
  287
);

-- Spring Offers (diving, trekking, city nature)
INSERT INTO offers (
  title, description, short_description, destination, country, duration, price, original_price,
  images, meals, trip_type, season, is_last_minute, accommodation, transport, rating, review_count
) VALUES
(
  'Nurkowanie w Morzu Czerwonym - Sharm el-Sheikh',
  'Raj dla nurków! Krystalicznie czysta woda, kolorowe rafy koralowe, egzotyczne ryby. Codzienne wyprawy nurkowe z instruktorem PADI. Możliwość kursu nurkowania dla początkujących. Wieczorny relaks na plaży.',
  'Nurkowanie na rafach koralowych Morza Czerwonego',
  'Sharm el-Sheikh',
  'Egipt',
  10,
  2899,
  3499,
  ARRAY['https://images.pexels.com/photos/3881104/pexels-photo-3881104.jpeg', 'https://images.pexels.com/photos/2404370/pexels-photo-2404370.jpeg'],
  'AI',
  'adventure',
  'spring',
  false,
  'Hotel 4* przy plaży',
  'Samolot + transfery',
  4.7,
  198
),
(
  'Trekking w Himalajach - Pokhara',
  'Niezapomniana przygoda w Nepalu! Trekking do bazy Annapurny przez malownicze wioski sherpa. Wschody słońca nad ośmiotysięcznikami, spotkania z lokalną kulturą. Doświadczeni przewodnicy górscy i porterzy.',
  'Ekspedycja trekkingowa do bazy Annapurny',
  'Pokhara',
  'Nepal',
  14,
  5899,
  6899,
  ARRAY['https://images.pexels.com/photos/2259232/pexels-photo-2259232.jpeg', 'https://images.pexels.com/photos/1366630/pexels-photo-1366630.jpeg'],
  'BB',
  'adventure',
  'spring',
  false,
  'Tea houses i hotel',
  'Samolot + lokalne transfery',
  4.9,
  145
),
(
  'Trekking w Portugalii - Madera',
  'Wyspa wiecznej wiosny! Trekking wzdłuż levadas (kanałów irygacyjnych) przez subtropikalne lasy. Spektakularne klify nad oceanem, wodospady, endemiczne rośliny. Łagodny klimat przez cały rok.',
  'Trekking po Maderze - wyspa wiecznej wiosny',
  'Funchal',
  'Portugalia',
  8,
  3299,
  3899,
  ARRAY['https://images.pexels.com/photos/1450353/pexels-photo-1450353.jpeg', 'https://images.pexels.com/photos/3155583/pexels-photo-3155583.jpeg'],
  'BB',
  'adventure',
  'spring',
  false,
  'Hotel 3* w Funchal',
  'Samolot + wynajęty samochód',
  4.6,
  112
),
(
  'Nurkowanie w Tajlandii - Koh Tao',
  'Mekka nurków w Azji! Koh Tao oferuje najlepsze warunki do nauki nurkowania w Tajlandii. Ciepła woda, bogactwo życia morskiego, profesjonalne centra nurkowe. Po nurkowaniu relaks na rajskich plażach.',
  'Kurs nurkowania PADI na Koh Tao',
  'Koh Tao',
  'Tajlandia',
  12,
  4299,
  4999,
  ARRAY['https://images.pexels.com/photos/1032650/pexels-photo-1032650.jpeg', 'https://images.pexels.com/photos/3220370/pexels-photo-3220370.jpeg'],
  'BB',
  'adventure',
  'spring',
  false,
  'Bungalow przy plaży',
  'Samolot + ferry',
  4.8,
  234
),
(
  'City Nature - Barcelona i Montserrat',
  'Połączenie miejskiego życia z górskimi przygodami! Zwiedzanie Barcelony (Sagrada Familia, Park Güell), następnie trekking w górach Montserrat. Wspinaczka, via ferrata, katalońska kuchnia.',
  'Barcelona i trekking w górach Montserrat',
  'Barcelona',
  'Hiszpania',
  6,
  2499,
  2999,
  ARRAY['https://images.pexels.com/photos/1388030/pexels-photo-1388030.jpeg', 'https://images.pexels.com/photos/3041347/pexels-photo-3041347.jpeg'],
  'BB',
  'culture',
  'spring',
  false,
  'Hotel 4* w centrum',
  'Samolot + metro',
  4.7,
  167
);

-- Summer Offers (sailing, beach, water sports)
INSERT INTO offers (
  title, description, short_description, destination, country, duration, price, original_price,
  images, meals, trip_type, season, is_last_minute, accommodation, transport, rating, review_count
) VALUES
(
  'Rejs żaglowy po Cykladach - Grecja',
  'Żegluj między greckimi wyspami! Santorini, Mykonos, Paros, Naxos - białe domki, błękitne kopuły, krystaliczne zatoki. Nocujesz na jachcie, gotujesz świeże ryby, pływasz w ukrytych zatoczkach. Bez doświadczenia - sternik pokazu wszystko!',
  'Tygodniowy rejs żaglowy po Cykladach',
  'Ateny',
  'Grecja',
  7,
  3899,
  4599,
  ARRAY['https://images.pexels.com/photos/1410489/pexels-photo-1410489.jpeg', 'https://images.pexels.com/photos/2412609/pexels-photo-2412609.jpeg'],
  'none',
  'adventure',
  'summer',
  false,
  'Kabina na jachcie',
  'Samolot + jacht',
  4.9,
  178
),
(
  'Sporty wodne w Chorwacji - Split',
  'Adrenalina na wodzie! Kitesurfing, windsurfing, wakeboarding, kayaking. Profesjonalni instruktorzy, sprzęt na miejscu. Wieczorami spacery po starówce Splitu, świeże owoce morza, chorwackie wina.',
  'Obóz sportów wodnych w Dalmacji',
  'Split',
  'Chorwacja',
  10,
  3299,
  3899,
  ARRAY['https://images.pexels.com/photos/1430672/pexels-photo-1430672.jpeg', 'https://images.pexels.com/photos/2404370/pexels-photo-2404370.jpeg'],
  'HB',
  'adventure',
  'summer',
  false,
  'Hotel 3* przy plaży',
  'Autobus + ferry',
  4.7,
  145
),
(
  'Malediwy - Райski relaks na plaży',
  'Turkusowa laguna, białe plaże, palmy kokosowe. Snorkeling z rekinami wielorybimi, nurkowanie, SPA nad oceanem. Luksusowy resort all-inclusive, bungalowy nad wodą. Idealny wyjazd marzeń!',
  'Luksusowy wypoczynek na Malediwach',
  'Male',
  'Malediwy',
  10,
  11899,
  13999,
  ARRAY['https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg', 'https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg'],
  'AI',
  'relax',
  'summer',
  false,
  'Bungalow nad wodą 5*',
  'Samolot + łódź',
  5.0,
  412
),
(
  'Karaiby - Rejs pod żaglami',
  'Przepłyń karaibskie wody! Antigua, Dominika, Martinique - każda wyspa to inna kultura. Nurkowanie z żółwiami, degustacja rumu, reggae na plaży. Jacht z pełnym wyposażeniem i doświadczonym kapitanem.',
  'Dwutygodniowy rejs po Karaibach',
  'Antigua',
  'Antigua i Barbuda',
  14,
  8899,
  10499,
  ARRAY['https://images.pexels.com/photos/1032650/pexels-photo-1032650.jpeg', 'https://images.pexels.com/photos/2412610/pexels-photo-2412610.jpeg'],
  'none',
  'adventure',
  'summer',
  false,
  'Kabina na jachcie',
  'Samolot + jacht',
  4.8,
  198
),
(
  'Bali - Surfing i plaża',
  'Raj surferów! Uluwatu, Canggu, Seminyak - najlepsze fale w Indonezji. Szkoła surfingu dla początkujących, warsztaty z doświadczonymi surferami. Wieczorne zachody słońca, balijskie masaże, świątynie.',
  'Obóz surfingowy na Bali',
  'Canggu',
  'Indonezja',
  14,
  4899,
  5699,
  ARRAY['https://images.pexels.com/photos/1654489/pexels-photo-1654489.jpeg', 'https://images.pexels.com/photos/2404370/pexels-photo-2404370.jpeg'],
  'BB',
  'adventure',
  'summer',
  false,
  'Villa przy plaży',
  'Samolot + transfery',
  4.9,
  267
);

-- Autumn Offers (city break, culture, gastronomy)
INSERT INTO offers (
  title, description, short_description, destination, country, duration, price, original_price,
  images, meals, trip_type, season, is_last_minute, accommodation, transport, rating, review_count
) VALUES
(
  'Paryż - City Break Kulturalny',
  'Stolica sztuki i mody! Luwr, Muzeum d''Orsay, Wieża Eiffla, spacery po Montmartre. Degustacja win w kawiarniach, croissanty, makaroniki. Jesienny Paryż w kolorach złota i czerwieni.',
  'Weekend kulturalny w Paryżu',
  'Paryż',
  'Francja',
  4,
  1899,
  2299,
  ARRAY['https://images.pexels.com/photos/2344/france-landmark-lights-night.jpg', 'https://images.pexels.com/photos/338515/pexels-photo-338515.jpeg'],
  'BB',
  'culture',
  'autumn',
  false,
  'Hotel 4* w centrum',
  'Samolot',
  4.8,
  234
),
(
  'Rzym - Kultura i Gastronomia',
  'Wieczne Miasto jesienią! Koloseum, Watykан, Fontanna di Trevi bez tłumów. Degustacja autentycznej pizzy, gelato, wina Chianti. Kursy gotowania włoskiego, spacery po Trastevere.',
  'City break w Rzymie z warsztatami kulinarnymi',
  'Rzym',
  'Włochy',
  5,
  2299,
  2799,
  ARRAY['https://images.pexels.com/photos/2064827/pexels-photo-2064827.jpeg', 'https://images.pexels.com/photos/1797161/pexels-photo-1797161.jpeg'],
  'BB',
  'culture',
  'autumn',
  false,
  'Hotel 4* przy Koloseum',
  'Samolot',
  4.9,
  289
),
(
  'Praga - Magiczny City Break',
  'Złota Praga jesienią! Zamek Praski, Most Karola, Stare Miasto. Czechskie piwo, tradycyjne restauracje, jazz cluby. Spacery po jesiennych parkach, tajemnicze zakamarki miasta.',
  'Weekend w jesiennej Pradze',
  'Praga',
  'Czechy',
  4,
  1299,
  1599,
  ARRAY['https://images.pexels.com/photos/2091166/pexels-photo-2091166.jpeg', 'https://images.pexels.com/photos/3014856/pexels-photo-3014856.jpeg'],
  'BB',
  'culture',
  'autumn',
  false,
  'Hotel 3* Stare Miasto',
  'Autobus',
  4.7,
  178
),
(
  'Barcelona - Kultura Katalońska',
  'Gaudi, tapasy, flamenco! Sagrada Familia, Park Güell, Las Ramblas. Degustacja win w Penedes, paella nad morzem, nocne życie. Jesień to idealny czas - ciepło bez upału.',
  'City break w Barcelonie z degustacjami',
  'Barcelona',
  'Hiszpania',
  5,
  2099,
  2499,
  ARRAY['https://images.pexels.com/photos/1388030/pexels-photo-1388030.jpeg', 'https://images.pexels.com/photos/3757144/pexels-photo-3757144.jpeg'],
  'BB',
  'culture',
  'autumn',
  false,
  'Hotel 4* dzielnica Eixample',
  'Samolot',
  4.8,
  245
),
(
  'Budapeszt - Termy i Gastronomia',
  'Perła Dunaju! Łaźnie termalne Szechenyi, Parlament, Baszta Rybacka. Węgierska kuchnia - gulasz, langosz, wino Tokaji. Wieczorny rejs po Dunaju, ruin bary, romantyczne mosty.',
  'City break z termami i degustacjami',
  'Budapeszt',
  'Węgry',
  4,
  1499,
  1799,
  ARRAY['https://images.pexels.com/photos/2363/france-landmark-lights-night.jpg', 'https://images.pexels.com/photos/2031706/pexels-photo-2031706.jpeg'],
  'BB',
  'culture',
  'autumn',
  false,
  'Hotel 3* nad Dunajem',
  'Samolot',
  4.6,
  156
);
